#!/usr/bin/env python3
"""Pre-AppRun environment snapshot (release PRD R61, the R20 follow-up).

Upstream's AppRun exports variables that only make sense for FreeCAD inside
the mounted image -- QT_QPA_PLATFORM=xcb, PYTHONHOME=<image>/usr, a bundled
SSL_CERT_FILE, ... A terminal or a `claude` child started from Atech Atelier
inherits them. Stripping them is not enough: when the user had their own
value (QT_QPA_PLATFORM=wayland, a corporate SSL_CERT_FILE) that value is
already overwritten by the time Python runs, so it cannot be restored from
inside the app.

So the build inserts a block as the first thing AppRun runs, BEFORE any
upstream export, which records:

    ATECH_APPRUN_SET="PREFIX PYTHONHOME ..."   the names AppRun is about to
                                               export, MEASURED from this
                                               AppRun's own export lines
    ATECH_PRE_APPRUN_<NAME>=<value>            the user's value, only for
                                               names that were set before

A name listed in ATECH_APPRUN_SET without an ATECH_PRE_APPRUN_<NAME> was
unset before AppRun and must be removed, not emptied. `restore()` below is
the reference consumer; acadagent/terminal.py clean_env() is expected to do
the same (WS-SHELL).

    python3 branding/apprun_env.py patch <AppRun>   insert the block (idempotent)
    python3 branding/apprun_env.py names <AppRun>   print the measured names
"""
import re
import sys

PREFIX = "ATECH_PRE_APPRUN_"
LIST_VAR = "ATECH_APPRUN_SET"
MARK = "# --- Atech: pre-AppRun environment snapshot (release PRD R61) ---"

# An active `export NAME=...` line. Commented-out exports (upstream ships
# `# export LD_LIBRARY_PATH=...`) do not run, so they are not listed.
_EXPORT = re.compile(r"^[ \t]*export[ \t]+([A-Za-z_][A-Za-z0-9_]*)=", re.M)


def exported_names(src):
    """Names the script exports, in first-seen order."""
    seen = []
    for m in _EXPORT.finditer(src):
        n = m.group(1)
        if n not in seen and not n.startswith(PREFIX) and n != LIST_VAR:
            seen.append(n)
    return seen


def snapshot_block(names):
    for n in names:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", n):
            raise ValueError("not a shell variable name: %r" % n)
    return "\n".join([
        MARK,
        "# Records the caller's values of every variable this AppRun exports,",
        "# so children the user types into can get their own environment back.",
        "# Generated by branding/apprun_env.py from this file's export lines.",
        '%s="%s"' % (LIST_VAR, " ".join(names)),
        "for _atech_v in $%s; do" % LIST_VAR,
        '    if [ -n "${!_atech_v+x}" ]; then',
        '        export "%s${_atech_v}=${!_atech_v}"' % PREFIX,
        "    else",
        "        # unset here: a snapshot inherited from an outer Atech Atelier must",
        "        # not stand in for a value this caller never had",
        '        unset "%s${_atech_v}"' % PREFIX,
        "    fi",
        "done",
        "unset _atech_v",
        "export %s" % LIST_VAR,
        "# --- end snapshot ---",
    ])


def insert_snapshot(src):
    """Return `src` with the snapshot block after the shebang line."""
    if MARK in src:
        return src
    if not src.startswith("#!"):
        raise ValueError("AppRun has no shebang line; its shape changed")
    names = exported_names(src)
    if not names:
        raise ValueError("AppRun exports nothing; its shape changed")
    first, rest = src.split("\n", 1)
    if "bash" not in first:
        # ${!name+x} is a bash expansion.
        raise ValueError("AppRun is not a bash script: %r" % first)
    return first + "\n" + snapshot_block(names) + "\n" + rest


def restore(env):
    """Reference consumer: the environment as it was before AppRun.

    Returns a new dict. Names AppRun set are put back to the caller's value,
    or removed when the caller had none; the snapshot variables themselves
    are dropped. Everything else is left alone."""
    env = dict(env)
    names = env.pop(LIST_VAR, "").split()
    for n in names:
        key = PREFIX + n
        if key in env:
            env[n] = env[key]
        else:
            env.pop(n, None)
    for k in [k for k in env if k.startswith(PREFIX)]:
        env.pop(k)
    return env


def main(argv):
    if len(argv) != 2 or argv[0] not in ("patch", "names"):
        sys.stderr.write(__doc__)
        return 2
    path = argv[1]
    with open(path, encoding="utf-8") as fh:
        src = fh.read()
    if argv[0] == "names":
        print(" ".join(exported_names(src)))
        return 0
    out = insert_snapshot(src)
    if out != src:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(out)
    print("APPRUN_SNAPSHOT %s" % " ".join(exported_names(src)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
