#!/usr/bin/env python3
"""Generate every Atech Atelier brand asset from two sources of truth.

    geometry : the atech.dev logo PNGs (vendored in brand/assets/source),
               traced (brand/tools/trace.py)
    colour   : brand/tokens.py, ported from the frontend's globals.css

Nothing here is drawn by hand. The previous branding/assets/atech_logo.svg
was — a blue-to-purple gradient chevron "A" whose colours (#5AA2FF,
#9A6BFF, #0F1017, #E9EBF3) appear NOWHERE in the frontend. It was not the
Atech mark; it was a plausible-looking substitute for one, which is
CLAUDE.md failure pattern P1. This script exists so that cannot recur:
the geometry can only come from the real artwork, and every colour can
only come from the token table.

Outputs (brand/assets/), each in a light and a dark variant:

    atech_icon-{mode}.svg     the mark alone, square, for WindowIcon
    atech_logo-{mode}.svg     mark + "Atech.dev" wordmark, for ProgramLogo
    atech_splash-{mode}.svg   the splash screen

Run:  python3 brand/tools/build_brand.py [--check]
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

import tokens
import trace as tracer

HERE = os.path.dirname(os.path.abspath(__file__))
BRAND = os.path.dirname(HERE)
ROOT = os.path.dirname(BRAND)
ASSETS = os.path.join(BRAND, "assets")

# Vendored from the atech.dev frontend (public/), provenance in SOURCE there.
# Never read from a sibling checkout: a clean clone must build its own brand.
ARTWORK = os.path.join(ASSETS, "source")
MARK_PNG = os.path.join(ARTWORK, "atech_mark_black.png")     # 252x320 portrait
LOCKUP_PNG = os.path.join(ARTWORK, "atech_lockup_black.png")   # 464x150 horizontal

# MEASURED 2026-09-24: in the 464x150 lockup, columns 76..142 are entirely
# empty — the gutter between the mark and the wordmark. Splitting there gives
# us the wordmark as geometry, so the logo does not depend on the Sen font
# being installed on the user's machine.
LOCKUP_SPLIT_X = 100

GENERATED_BY = "brand/tools/build_brand.py"

# The product name (owner, 2026-10-03; ADR-005). The splash draws the
# wordmark as traced geometry ("Atech.dev"), so only the second word is text.
PRODUCT = "Atech Atelier"
PRODUCT_WORD = PRODUCT.split(" ", 1)[1].upper()   # "ATELIER"


def _rings(png):
    """Trace `png` and return its rings as point arrays, plus source size."""
    a = tracer._alpha(png)
    h, w = a.shape
    ap = np.pad(a, 1, mode="constant")
    out = []
    for r in tracer._contours(ap, tracer.LEVEL):
        r = r - 1.0
        area = 0.5 * abs(np.dot(r[:, 0], np.roll(r[:, 1], -1))
                         - np.dot(r[:, 1], np.roll(r[:, 0], -1)))
        if area < 4:
            continue
        out.append(tracer._rdp(r, tracer.EPS))
    return out, (w, h)


def _bbox(rings):
    xs = np.concatenate([r[:, 0] for r in rings])
    ys = np.concatenate([r[:, 1] for r in rings])
    return xs.min(), ys.min(), xs.max(), ys.max()


def _xform(rings, dx=0.0, dy=0.0, s=1.0):
    return [np.column_stack([(r[:, 0] + dx) * s, (r[:, 1] + dy) * s])
            for r in rings]


def _d(rings):
    return tracer._path_d(rings)


def mark_geometry():
    """The mark alone, normalised so its bbox starts at 0,0."""
    rings, _ = _rings(MARK_PNG)
    x0, y0, x1, y1 = _bbox(rings)
    return _xform(rings, -x0, -y0), (x1 - x0, y1 - y0)


def lockup_geometry():
    """(mark_rings, word_rings, sizes) from the horizontal lockup.

    Both are normalised against the SAME origin so their relative placement
    and scale are preserved exactly as drawn — re-laying them out by hand
    would be inventing kerning the brand already decided.
    """
    rings, _ = _rings(LOCKUP_PNG)
    mark = [r for r in rings if r[:, 0].mean() < LOCKUP_SPLIT_X]
    word = [r for r in rings if r[:, 0].mean() >= LOCKUP_SPLIT_X]
    if not mark or not word:
        raise RuntimeError(
            f"lockup split at x={LOCKUP_SPLIT_X} produced "
            f"{len(mark)} mark rings and {len(word)} wordmark rings; "
            "the source artwork has changed — re-measure the gutter")
    x0, y0, x1, y1 = _bbox(rings)
    return (_xform(mark, -x0, -y0), _xform(word, -x0, -y0),
            (x1 - x0, y1 - y0))


def _svg(w, h, body, title):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '
            f'{w:.2f} {h:.2f}" width="{w:.0f}" height="{h:.0f}" '
            f'role="img" aria-label="{title}">\n'
            f'  <!-- GENERATED by {GENERATED_BY} — do not edit.\n'
            f'       Geometry traced from the atech.dev logo artwork;\n'
            f'       colour from brand/tokens.py. -->\n'
            f'{body}\n</svg>\n')


def build_icon(mode):
    """The mark alone on a rounded plate — WindowIcon and the taskbar."""
    p = tokens.palette(mode)
    rings, (mw, mh) = mark_geometry()
    S = 64.0
    pad = 11.0
    s = min((S - 2 * pad) / mw, (S - 2 * pad) / mh)
    # Scale first, then centre IN SCALED SPACE. _xform applies the translation
    # before the scale, so folding both into one call would scale the centring
    # offset too and park the mark in the corner. Two calls, one job each.
    rings = _xform(rings, 0, 0, s)
    x0, y0, x1, y1 = _bbox(rings)
    rings = [np.column_stack([r[:, 0] + (S - (x1 - x0)) / 2 - x0,
                              r[:, 1] + (S - (y1 - y0)) / 2 - y0])
             for r in rings]
    body = (f'  <rect x="1" y="1" width="62" height="62" rx="14" '
            f'fill="{p["panel"]}" stroke="{p["line"]}" stroke-width="1.5"/>\n'
            f'  <path d="{_d(rings)}" fill="{p["text"]}" '
            f'fill-rule="evenodd"/>')
    return _svg(S, S, body, "Atech Atelier")


def build_logo(mode):
    """Mark + wordmark, as drawn in the atech.dev lockup."""
    p = tokens.palette(mode)
    mark, word, (w, h) = lockup_geometry()
    body = (f'  <path d="{_d(mark)}" fill="{p["text"]}" fill-rule="evenodd"/>\n'
            f'  <path d="{_d(word)}" fill="{p["text"]}" fill-rule="evenodd"/>')
    return _svg(w, h, body, "Atech.dev")


def build_splash(mode):
    """Splash screen. 480x300, the proportion FreeCAD's splash expects.

    The mark's own silhouette is the structure: a swept curve terminating in
    a hard vertical. That vertical becomes the rule under the wordmark, so
    the layout is derived from the logo rather than decorated with it.
    """
    p = tokens.palette(mode)
    W, H = 480.0, 300.0
    mark, word, (lw, lh) = lockup_geometry()
    s = 236.0 / lw
    ox, oy = 40.0, 104.0
    mark = _xform(mark, ox / s, oy / s, s)
    word = _xform(word, ox / s, oy / s, s)
    rule_y = oy + lh * s + 22.0
    body = (
        f'  <rect width="{W:.0f}" height="{H:.0f}" fill="{p["base"]}"/>\n'
        f'  <path d="{_d(mark)}" fill="{p["text"]}" fill-rule="evenodd"/>\n'
        f'  <path d="{_d(word)}" fill="{p["text"]}" fill-rule="evenodd"/>\n'
        f'  <rect x="{ox:.0f}" y="{rule_y:.0f}" width="236" height="1" '
        f'fill="{p["line"]}"/>\n'
        f'  <rect x="{ox:.0f}" y="{rule_y:.0f}" width="28" height="1" '
        f'fill="{p["accent"]}"/>\n'
        f'  <text x="{ox:.0f}" y="{rule_y + 22:.0f}" '
        f'font-family="{tokens.FONT_DISPLAY}, {tokens.FONT_BODY}, sans-serif" '
        f'font-size="13" font-weight="600" letter-spacing="0.08em" '
        f'fill="{p["muted"]}">{PRODUCT_WORD}</text>\n'
        # The product line (owner, 2026-09-25): says what the app is built
        # on. No version number: that lives in upstream.env and in the
        # About box, and a typed copy here would drift from it. Sits under
        # the product word, well above FreeCAD's own loading messages at the bottom.
        f'  <text x="{ox:.0f}" y="{rule_y + 42:.0f}" '
        f'font-family="{tokens.FONT_BODY}, sans-serif" '
        f'font-size="11" fill="{p["muted"]}">powered by FreeCAD</text>')
    return _svg(W, H, body, f"{PRODUCT}, powered by FreeCAD")


BUILDERS = {"icon": build_icon, "logo": build_logo, "splash": build_splash}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the trace against the source artwork and "
                         "exit non-zero on regression; write nothing")
    args = ap.parse_args()

    for png in (MARK_PNG, LOCKUP_PNG):
        if not os.path.exists(png):
            sys.exit(f"FAIL source artwork missing: {png}")

    # GATE: the trace must still reproduce the source. This is the only check
    # that can catch a silently-wrong mark, so it runs on every build.
    ok = True
    for name, png in (("mark", MARK_PNG), ("lockup", LOCKUP_PNG)):
        d, size, st = tracer.trace(png)
        m = tracer.rasterize_check(d, size, png)
        tol = tracer.tolerance_for(png)
        bad = (m["mean_abs_err"] > tol
               or abs(m["area_delta_px"]) / m["ref_area_px"]
               > tracer.TOL_AREA_DELTA_FRAC)
        ok = ok and not bad
        print(f"[{'FAIL' if bad else ' OK ' }] trace {name:7} "
              f"rings={st['rings_kept']:2d} pts={st['points']:4d} "
              f"mean_abs_err={m['mean_abs_err']:.5f}/{tol:.5f} "
              f"area_delta={m['area_delta_px']:+.1f}px "
              f"({100 * m['area_delta_px'] / m['ref_area_px']:+.2f}%)")
    if not ok:
        sys.exit("FAIL trace no longer reproduces the source artwork")

    if args.check:
        print("check only — no files written")
        return

    os.makedirs(ASSETS, exist_ok=True)
    written = []
    for mode in sorted(tokens.MODES):
        for kind, fn in BUILDERS.items():
            path = os.path.join(ASSETS, f"atech_{kind}-{mode}.svg")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(fn(mode))
            written.append(os.path.relpath(path, ROOT))
            print(f"[ OK ] wrote {written[-1]}")

    manifest = os.path.join(ASSETS, "brand_manifest.json")
    with open(manifest, "w", encoding="utf-8") as fh:
        json.dump({
            "generated_by": GENERATED_BY,
            "geometry_source": [os.path.relpath(MARK_PNG, ROOT),
                                os.path.relpath(LOCKUP_PNG, ROOT)],
            "colour_source": "brand/tokens.py",
            "trace": {"level": tracer.LEVEL, "eps": tracer.EPS},
            "assets": written,
            "palette": {m: tokens.palette(m) for m in sorted(tokens.MODES)},
        }, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"[ OK ] wrote {os.path.relpath(manifest, ROOT)}")


if __name__ == "__main__":
    main()
