#!/usr/bin/env python3
"""Generate the FreeCAD theme-parameter YAMLs for both modes.

FreeCAD 1.1 resolves its (upstream, unmodified) Gui/Stylesheets/FreeCAD.qss
against a parameters YAML. Branding through those tokens means we inherit
every upstream widget fix for free and cannot break a dialog we never
tested — the reasoning already recorded in the hand-written
"Atech Studio Dark.yaml" (the product's previous name) this replaced.

What changes here is only WHERE the colours come from: brand/tokens.py
rather than literals. The previous file's palette was #0F1017 / #E9EBF3 /
#5AA2FF -> #9A6BFF, described as matching the Atech brand. It did not —
none of those four appears anywhere in the atech.dev frontend.

THE ELEVATION RAMP STAYS PINNED. That is carried over verbatim as a
decision, not re-derived, and the original file explains why:
lighten()/darken() map to QColor::lighter()/darker(), which scale HSV
*value* MULTIPLICATIVELY, so every derived token is proportional to
PrimaryColor's V. On a dark base that collapsed contrast (ActiveTab vs
InActiveTab measured 1.01 — a selection conveying nothing) and derived
GeneralBorderColor DARKER than the background, so borders did not render.
Raised planes are therefore explicit hex, computed here by a fixed
luminance ladder rather than by Qt's multiplicative one.

Run:  python3 brand/tools/build_theme.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BRAND = os.path.dirname(HERE)
ROOT = os.path.dirname(BRAND)
sys.path.insert(0, BRAND)

import tokens

sys.path.insert(0, HERE)
import qss

THEMEDIR = os.path.join(ROOT, "branding", "assets", "theme")
# The theme NAME is what FreeCAD's preferences list and what a profile's
# BaseApp/Preferences/MainWindow/Theme stores. Renamed with the product
# (ADR-005); AppRun's migration rewrites the old name in a copied profile.
PRODUCT = "Atech Atelier"
NAMES = {"light": PRODUCT + " Light.yaml", "dark": PRODUCT + " Dark.yaml"}
# Files this generator wrote under the previous product name. Removed on a
# write so the installer cannot pick a stale theme up by globbing.
RETIRED = ("Atech Studio Light.yaml", "Atech Studio Dark.yaml")

TEMPLATE = '''\
# {title} — theme parameters for FreeCAD 1.1's parametrized stylesheet.
#
# GENERATED by brand/tools/build_theme.py from brand/tokens.py.
# DO NOT EDIT: the next build overwrites it. Change brand/tokens.py.
#
# This is NOT a hand-written stylesheet. FreeCAD 1.1 migrated to a token
# system: Gui/Stylesheets/FreeCAD.qss is the (upstream, unmodified) sheet,
# and this YAML supplies the colours it resolves via
# replaceVariablesInQss(). Branding through tokens means we inherit every
# upstream widget fix for free and cannot break a dialog we never tested.
#
# Derived from upstream "FreeCAD {upstream}.yaml".
#
# ELEVATION RAMP IS PINNED, NOT DERIVED — carried over deliberately.
# lighten()/darken() map to QColor::lighter()/darker(), which scale HSV
# *value* MULTIPLICATIVELY (Gui/StyleParameters/Parser.cpp), so every
# derived token is proportional to PrimaryColor's V. MEASURED on the
# previous dark palette: button face contrast 1.13 vs bg (upstream gets
# 1.27), ActiveTab-vs-InActiveTab 1.01 — a selection conveying nothing —
# and GeneralBorderColor derived DARKER than the background, so borders did
# not render at all. Raised planes are explicit hex on the Atech surfaces.
#
# Installed to <AppHomePath>/share/Gui/Stylesheets/parameters/ by
# branding/build_appimage.sh; selected via the MainWindow/Theme preference.

3DViewBackgroundRefColor: "@BackgroundColor"
ButtonBackgroundHooverColor: "@ButtonTopBackgroundColor"
ButtonBorderColor: "@GeneralBorderColor"
ButtonBorderHooverColor: "@GeneralBorderColor"
ButtonBottomBackgroundColor: "@PrimaryColorLighten2"
ButtonTopBackgroundColor: "@PrimaryColorLighten3"
CheckedButtonBottomBackgroundColor: "darken(@ButtonBottomBackgroundColor, 5)"
CheckedButtonTopBackgroundColor: "darken(@ButtonTopBackgroundColor, 5)"
DefaultButtonBottomBackgroundColor: "blend(@ButtonBottomBackgroundColor, @AccentColor, 10)"
DefaultButtonTopBackgroundColor: "blend(@ButtonTopBackgroundColor, @AccentColor, 10)"
DefaultButtonBorderColor: "blend(@ButtonBorderColor, @AccentColor, 20)"
ToolButtonCheckedBorderColor: "@PrimaryColorLighten5"
ToolButtonCheckedBackground: "@CheckedButtonTopBackgroundColor"
CheckBoxBackgroundColor: "@TextEditFieldBackgroundColor"

AccentColor: "{accent}"
AccentColor2: "{accent2}"
BackgroundColor: "{base}"
GeneralBorderColor: "{line_strong}"

PrimaryColor: "{base}"
PrimaryColorLighten2: "{lift2}"
PrimaryColorLighten3: "{lift3}"
PrimaryColorLighten4: "{lift4}"
PrimaryColorLighten5: "{lift5}"

SelectionColor: "{accent}"
TextEditFieldBackgroundColor: "{input_bg}"

SketcherConflictingConstraintsColor: "{fail}"
SketcherEmptySketchColor: "{text}"
SketcherFullyConstrainedColor: "{ok}"
SketcherMalformedConstraintsColor: "{fail}"
SketcherPartiallyRedundantConstraintsColor: "{accent}"
SketcherRedundantConstraintsColor: "{warn}"
SketcherSolverFailedColor: "{fail}"
SketcherUnderConstrainedColor: "{text}"

InActiveTabBackgroundColor: "{sunken}"
ActiveTabBackgroundColor: "{lift2}"
TextDisabledColor: "{dim}"
TextForegroundColor: "{text}"
TextUrlColor: "{accent}"

# --- Atech-only tokens ------------------------------------
# Not in any upstream sheet. Read by overlay/Atech Overlay.qss
# (brand/tools/qss.py OVERLAY_TOKENS), which styles the overlay
# panels' title bars in this mode's brand surfaces (release PRD R88).
AtechPanelColor: "{panel}"
AtechHoverColor: "{hover}"
AtechMutedColor: "{muted}"
# Resting title-bar icon colour, an upstream images_classic suffix
# (qss.OVERLAY_ICON): lightgray read too faintly on dark (R118).
AtechOverlayIconColor: "{overlay_icon}"
'''


def _rgb(h):
    h = h.lstrip("#")
    return [int(h[i:i + 2], 16) for i in (0, 2, 4)]


def _hex(rgb):
    return "#%02X%02X%02X" % tuple(max(0, min(255, round(c))) for c in rgb)


def ladder(base, toward, steps=(0.06, 0.11, 0.16, 0.24)):
    """The pinned elevation ramp: fixed fractions toward `toward`.

    Linear in sRGB and anchored to an explicit endpoint, so the step sizes
    do not depend on the base's HSV value — which is exactly the failure
    Qt's multiplicative lighter()/darker() produced on a dark palette.
    """
    b, t = _rgb(base), _rgb(toward)
    return [_hex([b[i] + (t[i] - b[i]) * f for i in range(3)])
            for f in steps]


def render(mode):
    p = tokens.palette(mode)
    # Raised planes move AWAY from the background: toward white on a dark
    # base, toward black on a light one. "Lighten" is upstream's token name,
    # not a direction we are obliged to follow on a light theme.
    toward = "#ffffff" if mode == "dark" else "#000000"
    lift2, lift3, lift4, lift5 = ladder(p["base"], toward)
    return TEMPLATE.format(
        title=f"{PRODUCT} {mode.capitalize()}",
        upstream="Dark" if mode == "dark" else "Light",
        accent=p["accent"].upper(),
        accent2=p["accent_pure"].upper(),
        base=p["base"].upper(),
        line_strong=p["line_strong"].upper(),
        input_bg=p["input_bg"].upper(),
        sunken=p["sunken"].upper(),
        text=p["text"].upper(),
        dim=p["dim"].upper(),
        ok=p["ok"].upper(),
        fail=p["fail"].upper(),
        warn=p["warn"].upper(),
        panel=p["panel"].upper(),
        hover=p["hover"].upper(),
        muted=p["muted"].upper(),
        overlay_icon=qss.OVERLAY_ICON[mode],
        lift2=lift2, lift3=lift3, lift4=lift4, lift5=lift5)


def contrast(a, b):
    def lum(h):
        c = [v / 255 for v in _rgb(h)]
        c = [v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
             for v in c]
        return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
    la, lb = lum(a), lum(b)
    la, lb = max(la, lb), min(la, lb)
    return (la + 0.05) / (lb + 0.05)


# Where upstream's own parameter files live inside the built tree. Used to
# guarantee TOKEN PARITY: FreeCAD.qss resolves @Token references at runtime and
# an absent token is NOT a fallback — the reference is simply unresolved. A
# generator that emits only the keys it sets silently forfeits the "inherit
# every upstream widget fix for free" property this file's own header claims.
#
# MEASURED 2026-09-24: the template emitted 38 keys against upstream's 66,
# dropping AccentBackgroundColor, AccentHoverColor, CheckBoxBorderColor and
# DialogBackgroundColor. Two of those are load-bearing for the accent work.
#
# Resolved, in order: --upstream DIR (build_appimage.sh passes the tree it just
# extracted), $ATECH_UPSTREAM_PARAMS, then this repo's default build tree.
_PARAMS_REL = os.path.join("usr", "share", "Gui", "Stylesheets", "parameters")
UPSTREAM_PARAMS = (os.environ.get("ATECH_UPSTREAM_PARAMS")
                   or os.path.join(ROOT, "dist", "build", "squashfs-root",
                                   _PARAMS_REL))


def _upstream_pairs(mode):
    """(key, value) from upstream's parameter file, in order. [] when absent."""
    name = "FreeCAD %s.yaml" % ("Dark" if mode == "dark" else "Light")
    path = os.path.join(UPSTREAM_PARAMS, name)
    if not os.path.isfile(path):
        return []
    out = []
    for line in open(path, encoding="utf-8"):
        raw = line.split("#")[0]
        if ":" in raw and not raw.startswith((" ", "\t")):
            k, _, v = raw.partition(":")
            out.append((k.strip(), v.strip()))
    return out


def backfill(text, mode):
    """Append every upstream key the template omits, at its upstream value.

    Parity by construction rather than by vigilance: our own values always
    win, because they are already in `text` and are not overwritten here.
    """
    pairs = _upstream_pairs(mode)
    if not pairs:
        return text, None          # CANNOT DETERMINE — say so, do not assume
    have = {ln.split(":", 1)[0].strip()
            for ln in text.splitlines()
            if ":" in ln and not ln.startswith(("#", " ", "\t"))}
    missing = [(k, v) for k, v in pairs if k not in have]
    if not missing:
        return text, 0
    block = ["", "# --- inherited from upstream, unchanged ------------------",
             "# Present so every @Token FreeCAD.qss references resolves. Our",
             "# own values above are NOT overridden by this block."]
    block += ["%s: %s" % (k, v) for k, v in missing]
    return text.rstrip("\n") + "\n" + "\n".join(block) + "\n", len(missing)


BUILTIN_TOKENS = {"ThemeAccentColor1", "ThemeAccentColor2",
                  "ThemeAccentColor3"}


def overlay_gaps(yaml_text):
    """Tokens the built overlay sheet references that `yaml_text` lacks.

    None when the sheet has not been built. Comments are stripped from the
    sheet first: its header may name tokens in prose."""
    path = os.path.join(BRAND, "assets", qss.OVERLAY_NAME)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        body = re.sub(r"/\*.*?\*/", "", fh.read(), flags=re.S)
    want = set(re.findall(r"@([A-Za-z0-9_]+)", body)) - BUILTIN_TOKENS
    have = {ln.split(":", 1)[0].strip() for ln in yaml_text.splitlines()
            if ":" in ln and not ln.startswith(("#", " ", "\t"))}
    return sorted(want - have)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--upstream", metavar="DIR",
                    help="upstream Gui/Stylesheets/parameters dir; when given "
                         "it MUST exist (a build that names its tree may not "
                         "fall back to CANNOT DETERMINE)")
    args = ap.parse_args()
    global UPSTREAM_PARAMS
    if args.upstream:
        if not os.path.isdir(args.upstream):
            sys.exit("FAIL upstream parameters dir not found: %s" % args.upstream)
        UPSTREAM_PARAMS = args.upstream

    os.makedirs(THEMEDIR, exist_ok=True)
    failed = False

    for mode in sorted(NAMES):
        text = render(mode)
        text, n_filled = backfill(text, mode)
        if n_filled is None:
            print("[????] %-5s token parity  CANNOT DETERMINE "
                  "(upstream parameters not found)" % mode)
        elif n_filled:
            print("[ OK ] %-5s token parity  backfilled %d upstream key(s)"
                  % (mode, n_filled))
        else:
            print("[ OK ] %-5s token parity  complete" % mode)
        path = os.path.join(THEMEDIR, NAMES[mode])
        rel = os.path.relpath(path, ROOT)

        # GATE: the ramp exists to make raised planes VISIBLE. Assert the
        # separation the previous palette silently lost — ActiveTab vs
        # InActiveTab measured 1.01 there, i.e. invisible.
        p = tokens.palette(mode)
        toward = "#ffffff" if mode == "dark" else "#000000"
        lift2, lift3, lift4, lift5 = ladder(p["base"], toward)
        tab = contrast(lift2, p["sunken"])
        btn = contrast(lift3, p["base"])
        border = contrast(p["line_strong"], p["base"])
        for label, got, want in (("tab separation", tab, 1.08),
                                 ("button vs bg", btn, 1.08),
                                 ("border vs bg", border, 1.08)):
            if got < want:
                failed = True
                print(f"[FAIL] {mode:5} {label:15} {got:.3f} < {want}")
            else:
                print(f"[ OK ] {mode:5} {label:15} {got:.3f}")

        # GATE (R88): every @Token the overlay sheet asks for must be a key
        # of THIS mode's YAML. Read from the sheet as written to disk by
        # build_qss.py and from the YAML text below, not from either
        # generator's tables, so a token renamed on one side fails here.
        # ThemeAccentColor1..3 are built-in parameters, not YAML keys.
        undefined = overlay_gaps(text)
        if undefined is None:
            failed = True
            print(f"[FAIL] {mode:5} overlay tokens  {qss.OVERLAY_NAME} not "
                  f"built (run build_qss.py first)")
        elif undefined:
            failed = True
            print(f"[FAIL] {mode:5} overlay tokens  undefined: "
                  f"{', '.join(undefined)}")
        else:
            print(f"[ OK ] {mode:5} overlay tokens  all defined")

        if args.check:
            if not os.path.exists(path):
                print(f"[FAIL] missing {rel}")
                failed = True
            else:
                with open(path, encoding="utf-8") as fh:
                    if fh.read() != text:
                        print(f"[FAIL] {rel} is stale")
                        failed = True
                    else:
                        print(f"[ OK ] {rel} matches the tokens")
            continue

        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"[ OK ] wrote {rel}")

    # Files written under the previous product name must not survive next to
    # the current ones: --check fails on them, a write removes them.
    for old in RETIRED:
        path = os.path.join(THEMEDIR, old)
        if not os.path.exists(path):
            continue
        rel = os.path.relpath(path, ROOT)
        if args.check:
            failed = True
            print(f"[FAIL] retired theme still present: {rel}")
        else:
            os.remove(path)
            print(f"[ OK ] removed retired {rel}")

    if failed:
        sys.exit("FAIL theme verification")


if __name__ == "__main__":
    main()
