"""Render the Atech Atelier Qt stylesheet for a given mode.

ONE template, TWO outputs. The stylesheet this replaces was maintained by
hand and said so in its own header:

    "Palette is the one already in acadagent/theme.py. One palette, two
     files, kept in sync by being written down in exactly one place: here
     and there with the same literals. If you change a colour, change both."

Two files holding the same literals, kept in sync by remembering to, is not
a single source of truth — it is two sources that currently agree. Adding a
light mode would have made it three. Here the literals exist once, in
brand/tokens.py, and every sheet is a pure function of them.

Selector coverage is carried over from that sheet unchanged, so nothing
already working is lost. DELIBERATELY THIN, for the reason it gave: FreeCAD's
own FreeCAD.qss is 2,722 lines with an @Token system, and forking it would
be a permanent merge burden for a palette change. We restyle only the
surfaces that carry the brand and let Qt's defaults handle the rest.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import tokens

TEMPLATE = """\
/*
 * Atech Atelier — {mode} theme.
 *
 * GENERATED by brand/tools/build_qss.py from brand/tokens.py.
 * DO NOT EDIT: the next build overwrites it. Change brand/tokens.py.
 *
 * Applied via the MainWindow/StyleSheet preference, seeded by
 * branding/assets/atech_user_template.cfg on first run. The dock-scoped
 * sheet in addon/AcadAgent/acadagent/theme.py remains the fallback for a
 * stock FreeCAD.
 *
 * Palette for this mode, ported from the atech.dev frontend:
 *
 *   base    {base}   window / dock background
 *   panel   {panel}   raised surface
 *   sunken  {sunken}   input wells
 *   line    {line}   borders
 *   text    {text}   primary text
 *   muted   {muted}   secondary text
 *   dim     {dim}   tertiary text
 *   accent  {accent}   focus and active tool
 *   ok      {ok}   pass
 *   fail    {fail}   fail  (louder than pass — CLAUDE.md R5)
 */

/* ---------------------------------------------------------------- shell */
QMainWindow,
QDockWidget,
QDialog {{
    background: {base};
    color: {text};
}}

QWidget {{
    font-family: {font_body};
}}

QMenuBar {{
    background: {panel};
    color: {text};
    border-bottom: 1px solid {line};
}}

QMenuBar::item {{
    background: transparent;
    padding: 5px 10px;
}}

QMenuBar::item:selected {{
    background: {hover};
    color: {text};
}}

QMenu {{
    background: {panel};
    color: {text};
    border: 1px solid {line};
    padding: 4px;
}}

QMenu::item:selected {{
    background: {hover};
}}

QMenu::separator {{
    height: 1px;
    background: {line};
    margin: 4px 8px;
}}

/* -------------------------------------------------------------- toolbar */
QToolBar {{
    background: {base};
    border: none;
    border-bottom: 1px solid {line};
    spacing: 2px;
    padding: 3px;
}}

QToolButton {{
    background: transparent;
    color: {text};
    border: 1px solid transparent;
    border-radius: 5px;
    padding: 4px;
}}

QToolButton:hover {{
    background: {hover};
    border-color: {line};
}}

QToolButton:checked,
QToolButton:pressed {{
    background: {hover};
    border-color: {accent};
    color: {accent};
}}

/* Dropdown tool buttons (Undo/Redo history, view menus, Part primitives).
   Once QToolButton carries a border, Qt's stylesheet style draws the
   ::menu-button sub-control itself, and with no rule for it the result was
   a solid black bar beside every dropdown (release PRD R51, dogfood D15).
   The arrow images are upstream's own, reached through the "qss:" search
   path FreeCAD registers for Gui/Stylesheets (StartupProcess.cpp). */
QToolButton[popupMode="1"] {{
    padding-right: 14px;
}}

QToolButton::menu-button {{
    background: transparent;
    border: 1px solid transparent;
    border-top-right-radius: 5px;
    border-bottom-right-radius: 5px;
    width: 12px;
}}

QToolButton::menu-button:hover {{
    background: {hover};
    border-left-color: {line};
}}

QToolButton::menu-button:pressed {{
    background: {hover};
}}

QToolButton::menu-arrow,
QToolButton::menu-indicator {{
    image: url(qss:images_classic/arrow-down-{arrow_icon}.svg);
    width: 8px;
    height: 8px;
}}

QToolButton::menu-indicator {{
    subcontrol-origin: padding;
    subcontrol-position: bottom right;
}}

/* ---------------------------------------------------------------- docks */
QDockWidget::title {{
    background: {panel};
    color: {muted};
    font-family: {font_display};
    font-weight: 600;
    letter-spacing: 0.06em;
    padding: 6px 10px;
    border-bottom: 1px solid {line};
}}

/* ------------------------------------------------------- tree and lists */
QTreeView,
QListView,
QTableView {{
    background: {panel};
    alternate-background-color: {sunken};
    color: {text};
    border: 1px solid {line};
    selection-background-color: {hover};
    selection-color: {text};
    outline: none;
}}

QHeaderView::section {{
    background: {sunken};
    color: {muted};
    border: none;
    border-right: 1px solid {line};
    border-bottom: 1px solid {line};
    padding: 5px 8px;
}}

/* ----------------------------------------------------------------- tabs */
QTabWidget::pane {{
    border: 1px solid {line};
    background: {panel};
}}

QTabBar::tab {{
    background: {base};
    color: {muted};
    border: 1px solid {line};
    border-bottom: none;
    padding: 6px 14px;
    margin-right: 2px;
}}

QTabBar::tab:selected {{
    background: {panel};
    color: {text};
    border-top: 2px solid {accent};
}}

/* --------------------------------------------------------------- inputs */
QLineEdit,
QPlainTextEdit,
QTextEdit,
QSpinBox,
QDoubleSpinBox,
Gui--QuantitySpinBox,
Gui--IntSpinBox,
QComboBox {{
    background: {input_bg};
    color: {text};
    border: 1px solid {input_border};
    border-radius: 5px;
    padding: 5px 8px;
    selection-background-color: {accent};
    selection-color: {btn_text};
}}

QLineEdit:focus,
QPlainTextEdit:focus,
QTextEdit:focus,
QSpinBox:focus,
QDoubleSpinBox:focus,
Gui--QuantitySpinBox:focus,
Gui--IntSpinBox:focus,
QComboBox:focus {{
    border-color: {accent};
}}

/* Spin boxes, FreeCAD's unit-aware ones included (every number in a task
   panel is a Gui::QuantitySpinBox). Once the box carries a border, Qt's
   stylesheet style draws the step buttons itself, and with no rule for them
   they rendered as blank dark slots with no arrows (R88 GUI pass). Arrow
   images are upstream's, as for the tool-button menus above. */
QSpinBox,
QDoubleSpinBox,
Gui--QuantitySpinBox,
Gui--IntSpinBox {{
    padding: 3px 18px 3px 8px;
}}

QSpinBox::up-button,
QDoubleSpinBox::up-button,
Gui--QuantitySpinBox::up-button,
Gui--IntSpinBox::up-button,
QSpinBox::down-button,
QDoubleSpinBox::down-button,
Gui--QuantitySpinBox::down-button,
Gui--IntSpinBox::down-button {{
    subcontrol-origin: border;
    width: 16px;
    background: transparent;
    border: none;
}}

QSpinBox::up-button,
QDoubleSpinBox::up-button,
Gui--QuantitySpinBox::up-button,
Gui--IntSpinBox::up-button {{
    subcontrol-position: top right;
}}

QSpinBox::down-button,
QDoubleSpinBox::down-button,
Gui--QuantitySpinBox::down-button,
Gui--IntSpinBox::down-button {{
    subcontrol-position: bottom right;
}}

QSpinBox::up-button:hover,
QDoubleSpinBox::up-button:hover,
Gui--QuantitySpinBox::up-button:hover,
Gui--IntSpinBox::up-button:hover,
QSpinBox::down-button:hover,
QDoubleSpinBox::down-button:hover,
Gui--QuantitySpinBox::down-button:hover,
Gui--IntSpinBox::down-button:hover {{
    background: {hover};
}}

QSpinBox::up-arrow,
QDoubleSpinBox::up-arrow,
Gui--QuantitySpinBox::up-arrow,
Gui--IntSpinBox::up-arrow {{
    image: url(qss:images_classic/arrow-up-{arrow_icon}.svg);
    width: 8px;
    height: 8px;
}}

QSpinBox::down-arrow,
QDoubleSpinBox::down-arrow,
Gui--QuantitySpinBox::down-arrow,
Gui--IntSpinBox::down-arrow {{
    image: url(qss:images_classic/arrow-down-{arrow_icon}.svg);
    width: 8px;
    height: 8px;
}}

/* Measurements are mono. Every number this app prints is a measured
   dimension, so the face is load-bearing, not decorative. */
QPlainTextEdit,
QTextEdit {{
    font-family: {font_mono};
}}

QComboBox QAbstractItemView {{
    background: {panel};
    color: {text};
    border: 1px solid {line};
    selection-background-color: {hover};
}}

/* -------------------------------------------------------------- buttons */
QPushButton {{
    background: {panel};
    color: {text};
    border: 1px solid {line_strong};
    border-radius: 5px;
    padding: 6px 14px;
}}

QPushButton:hover {{
    background: {hover};
}}

QPushButton:pressed {{
    background: {sunken};
}}

QPushButton:default {{
    background: {btn_bg};
    color: {btn_text};
    border-color: {btn_bg};
}}

QPushButton:default:hover {{
    background: {btn_bg_hover};
}}

QPushButton:disabled {{
    color: {dim};
    border-color: {line};
    background: {base};
}}

/* ------------------------------------------------------------ statusbar */
QStatusBar {{
    background: {panel};
    color: {muted};
    border-top: 1px solid {line};
}}

QStatusBar::item {{
    border: none;
}}

/* ----------------------------------------------------------- scrollbars */
QScrollBar:vertical {{
    background: {base};
    width: 12px;
    margin: 0;
}}

QScrollBar::handle:vertical {{
    background: {line_strong};
    border-radius: 6px;
    min-height: 28px;
}}

QScrollBar::handle:vertical:hover {{
    background: {dim};
}}

QScrollBar:horizontal {{
    background: {base};
    height: 12px;
    margin: 0;
}}

QScrollBar::handle:horizontal {{
    background: {line_strong};
    border-radius: 6px;
    min-width: 28px;
}}

QScrollBar::handle:horizontal:hover {{
    background: {dim};
}}

QScrollBar::add-line,
QScrollBar::sub-line,
QScrollBar::add-page,
QScrollBar::sub-page {{
    background: none;
    border: none;
    height: 0;
    width: 0;
}}

/* ------------------------------------------------------------- splitter */
QSplitter::handle {{
    background: {line};
}}

/* -------------------------------------------------------------- tooltip */
QToolTip {{
    background: {panel};
    color: {text};
    border: 1px solid {line_strong};
    padding: 4px 7px;
}}

/* ----------------------------------------------------------- task panel */
/* The boxes in the Tasks panel (QSint ActionGroup). Unstyled, they paint
   from Qt's default palette, which this sheet does not set: in the dark
   theme that was a light box with the white header text on it, unreadable
   (MEASURED in the R88 GUI pass, Part_Primitives). Only the surfaces and
   the text ON them are set here; everything inside keeps its own rules. */

/* The box itself (Gui::TaskView::TaskBox) fills its background from the
   same default palette, and only its rounded header and content corners
   let it through: 1-2 near-white pixels (MEASURED 221 and 230) at each
   dark header's top corners (release PRD R118). Transparent lets the
   panel's own ground show there instead. */
QSint--ActionGroup {{
    background: transparent;
}}

QSint--ActionGroup QFrame[class="header"] {{
    background: {sunken};
    border: 1px solid {line};
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
}}

QSint--ActionGroup QToolButton[class="header"] {{
    background: transparent;
    color: {text};
    border: none;
    font-weight: 600;
    text-align: left;
}}

QSint--ActionGroup QFrame[class="content"] {{
    background: {panel};
    border: 1px solid {line};
    border-top: none;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
}}

QSint--ActionGroup QFrame[class="content"] QLabel,
QSint--ActionGroup QFrame[class="content"] QGroupBox,
QSint--ActionGroup QFrame[class="content"] QCheckBox,
QSint--ActionGroup QFrame[class="content"] QRadioButton {{
    color: {text};
}}

QSint--ActionGroup QFrame[class="content"] QLabel:disabled,
QSint--ActionGroup QFrame[class="content"] QGroupBox:disabled,
QSint--ActionGroup QFrame[class="content"] QCheckBox:disabled,
QSint--ActionGroup QFrame[class="content"] QRadioButton:disabled {{
    color: {dim};
}}

/* The 1 px QFrame QSint puts between a box's header and its content paints
   in Qt's default mid grey (MEASURED 159,159,159 in both modes, a bright
   rule across every dark task box). The header's own border already closes
   the box; hidden as upstream FreeCAD.qss does. */
QSint--ActionGroup QFrame[class="separator"] {{
    min-height: 0;
    max-height: 0;
    border: none;
}}

/* -------------------------------------------------------------- overlay */
/* Title bars FreeCAD draws for docks and overlay panels (Model, Tasks,
   Report). OverlayToolButtons are fixed 17 px squares; the generic
   QToolButton rule above gave them 4 px padding and a 1 px border, which
   left 7 px for the icon, so the title-bar controls read as specks (release
   PRD R88). Inside an overlay panel the overlay sheet (render_overlay)
   takes over; these rules cover docks that are not overlaid. */
Gui--OverlayTitleBar {{
    background: {panel};
    color: {muted};
}}

Gui--OverlayToolButton {{
    background: transparent;
    border: 1px solid transparent;
    border-radius: 3px;
    padding: 0;
}}

Gui--OverlayToolButton:hover {{
    background: {hover};
    border-color: {line};
}}

Gui--OverlayToolButton:checked,
Gui--OverlayToolButton:pressed {{
    background: {hover};
    border-color: {accent};
}}

/* Their icons. Upstream sets these in FreeCAD.qss, which this sheet
   replaces; without them the buttons keep their built-in glyphs, which are
   black: invisible on the dark title bar (MEASURED: Float button max luma
   0 on the dark theme, release PRD R118). Resting colour per mode, as for
   the overlay sheet's AtechOverlayIconColor token; hover takes the theme's
   full-contrast icon colour. */
Gui--OverlayToolButton[objectName="OBTN Float"] {{
    image: url(qss:images_classic/float-{overlay_icon}.svg);
}}

Gui--OverlayToolButton[objectName="OBTN Float"]:hover {{
    image: url(qss:images_classic/float-{icons_color}.svg);
}}

Gui--OverlayToolButton[objectName="OBTN Overlay"] {{
    image: url(qss:images_classic/overlay-{overlay_icon}.svg);
}}

Gui--OverlayToolButton[objectName="OBTN Overlay"]:hover {{
    image: url(qss:images_classic/overlay-{icons_color}.svg);
}}

/* ------------------------------------------------------- dialog buttons */
/* The Close button of a task dialog (Part_Primitives and every other
   QDialogButtonBox) takes Qt's stock SP_DialogCloseButton icon, a black X:
   MEASURED mean luma 21 on the dark theme's buttons, where every other
   stock dialog icon is coloured and reads (R118). Qt's stylesheet style
   substitutes this icon when the property is set. */
QDialogButtonBox {{
    dialog-close-icon: url(qss:images_classic/close-{icons_color}.svg);
}}

/* ------------------------------------------------------------- progress */
QProgressBar {{
    background: {sunken};
    border: 1px solid {line};
    border-radius: 5px;
    text-align: center;
    color: {text};
}}

QProgressBar::chunk {{
    background: {accent};
    border-radius: 4px;
}}
"""


# ---------------------------------------------------------------------------
# The overlay sheet (release PRD R88).
#
# FreeCAD applies a SEPARATE stylesheet to its overlay panels (the Tasks panel
# floating over the 3D view): MainWindow/OverlayActiveStyleSheet names a file
# on the "overlay:" search path, OverlayManager.cpp (OverlayStyleSheet::update)
# reads it, resolves @Tokens against the active theme and calls setStyleSheet
# on each OverlayTabWidget. A widget's own sheet beats the application sheet,
# so nothing in AtechLight/AtechDark.qss can restyle a control that sheet also
# styles. Upstream's "Freecad Overlay.qss" fills a checked title button with
# @ThemeAccentColor1, which is our accent: a solid bright-green square.
#
# ONE file for both modes: colours are @Tokens, resolved by FreeCAD against
# "Atech Atelier Light/Dark.yaml" (brand/tools/build_theme.py), so it follows
# the theme the way upstream's does and holds no literal to drift. Rules not
# commented below are carried over from upstream 1.1.3 unchanged, because they
# are functional (transparent panes, the shadow effect, tab-bar anchoring).
# ---------------------------------------------------------------------------
OVERLAY_NAME = "Atech Overlay.qss"

OVERLAY_TEMPLATE = """\
/*
 * Atech Atelier — overlay panel sheet (Tasks, Report, ... over the 3D view).
 *
 * GENERATED by brand/tools/build_qss.py (brand/tools/qss.py). DO NOT EDIT.
 * Selected by MainWindow/OverlayActiveStyleSheet, seeded by
 * branding/assets/atech_user_template.cfg. Derived from FreeCAD 1.1.3's
 * Gui/Stylesheets/overlay/Freecad Overlay.qss (LGPL-2.1-or-later).
 *
 * Colours are theme tokens, resolved by FreeCAD against the active
 * "Atech Atelier Light/Dark" parameters, so one file serves both modes.
 */

Gui--DockWnd--ReportOutput,
Gui--TaskView--TaskView QScrollArea {
    border: none;
}

QTabWidget::pane {
    background-color: transparent;
    border: transparent;
}

QAbstractItemView {
    alternate-background-color: @PrimaryColor;
    color: @TextForegroundColor;
    border: 1px solid @GeneralBorderColor;
}

/* The panel's own title bar: brand panel surface, secondary text. */
Gui--OverlayTitleBar,
Gui--OverlaySplitterHandle {
    background-color: @AtechPanelColor;
    color: @AtechMutedColor;
}

/* FreeCAD 1.1.3 gives a dock inside an overlay panel its OWN title bar as
   well (MEASURED on the stock AppImage too: "Tasks" twice, one centred, one
   right-aligned). The panel's bar already names the dock and carries the
   panel controls, so the dock's caption is drawn in no colour; its two
   buttons (Overlay, Float) stay usable. OverlayTitleBar::paintEvent draws
   the caption with the widget's own pen, which "color" sets. */
Gui--OverlayTabWidget QDockWidget > Gui--OverlayTitleBar {
    color: transparent;
}

/* The Tasks panel's ground. Only painted when the panel is NOT in FreeCAD's
   transparent mode: in that mode OverlayTabWidget::_setOverlayMode sets
   WA_NoSystemBackground on every child, which suppresses any stylesheet
   background (MEASURED: this rule then changes no pixel), and the 3D view
   shows through the gaps between task boxes, including its corner axis
   labels ("stray x", R88). The template therefore seeds the right-hand
   panel opaque (DockWindows/OverlayRight/Transparent = 0); the eye button
   in the title bar still turns transparency back on. */
Gui--OverlayTabWidget Gui--TaskView--TaskPanel {
    background-color: @BackgroundColor;
}

/* Overwrites Properties panel to use the theme text. */
Gui--TreePanel QTreeView {
    background-color: @PrimaryColor;
    border: 0px solid @TextForegroundColor;
    color: @TextForegroundColor;
    gridline-color: @GeneralGridLinesColor;
    border-radius: 0px;
}

Gui--TreePanel QTreeView::item {
    color: @TextForegroundColor;
}

Gui--TreePanel QTreeView::item:disabled {
    color: @TextDisabledColor;
}

Gui--TreePanel QTreeView:disabled {
    color: @TextDisabledColor;
}

Gui--PropertyEditor--PropertyEditor {
    qproperty-itemBackground: @TextEditFieldBackgroundColor;
}

Gui--OverlayTabWidget Gui--TreePanel QTreeView::item {
    color: @TextForegroundColor;
}

Gui--OverlayTabWidget Gui--TreePanel QTreeView::item:disabled {
    color: @TextDisabledColor;
}

Gui--OverlayTabWidget {
    qproperty-effectColor: @3DViewBackgroundRefColor;
    qproperty-effectBlurRadius: 0;
    qproperty-effectOffsetX: 0;
    qproperty-effectOffsetY: 0;
    qproperty-effectWidth: 1;
    qproperty-effectHeight: 1;
    qproperty-enableEffect: 1;
}

Gui--OverlayTabWidget#OverlayBottom {
    qproperty-effectColor: @3DViewBackgroundRefColor;
    qproperty-effectBlurRadius: 0;
    qproperty-effectOffsetX: 0.0;
    qproperty-effectOffsetY: 0.0;
    qproperty-effectWidth: 1;
    qproperty-effectHeight: 1;
    qproperty-enableEffect: 1;
}

Gui--OverlayTabWidget::pane {
    background-color: transparent;
    border: transparent;
}

QSint--ActionGroup QFrame[class="content"] {
    border-bottom: 1px solid @GeneralBorderColor;
    border-left: 1px solid @GeneralBorderColor;
    border-right: 1px solid @GeneralBorderColor;
    border-top-left-radius: 0px;
    border-top-right-radius: 0px;
    border-bottom-left-radius: 3px;
    border-bottom-right-radius: 3px;
}

QSint--ActionGroup QFrame[class="header"] {
    border: 1px solid @GeneralBorderColor;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    border-bottom-left-radius: 0px;
    border-bottom-right-radius: 0px;
}

Gui--OverlayTabWidget::tab-bar:top,
Gui--OverlayTabWidget::tab-bar:bottom {
    left: 10px;
    alignment: left;
}

Gui--OverlayTabWidget::tab-bar:left,
Gui--OverlayTabWidget::tab-bar:right {
    top: 10px;
    alignment: top;
}

/* Upstream also set "background-color: red" here. OverlayProxyWidget
   paints itself (only the hint), so that rule never drew; dropped. */
Gui--OverlayProxyWidget {
    qproperty-hintColor: rgba(250, 250, 250, 0.6);
}

/* Title-bar controls, matching the application sheet's tool buttons:
   no padding (the button is a fixed 17 px square, so any padding shrinks
   the icon), hover = raised plane, checked = accent OUTLINE on a raised
   plane. Upstream filled checked with @ThemeAccentColor1 (R88). */
Gui--OverlayToolButton {
    background: transparent;
    border: 1px solid transparent;
    border-radius: 3px;
    padding: 0px;
}

Gui--OverlayToolButton:hover {
    background-color: @AtechHoverColor;
    border: 1px solid @GeneralBorderColor;
}

Gui--OverlayToolButton:pressed,
Gui--OverlayToolButton:checked {
    background-color: @AtechHoverColor;
    border: 1px solid @AccentColor;
}

Gui--OverlayToolButton:checked:hover {
    border: 1px solid @AccentColor;
    background-color: @PrimaryColorLighten2;
}

/* Resting icons: upstream's lightgray (#888) is a 136-luma glyph on the
   dark panel, the "low-contrast dock buttons" of R118, so the resting colour
   is the Atech token AtechOverlayIconColor (lightgray in light, white in
   dark). The dock's own Float button had no rule here at all and kept its
   built-in black glyph (MEASURED max luma 0 on dark). */
Gui--OverlayToolButton[objectName="OBTN Transparent"] {
    image: url(qss:@IconsLocationFolderName/transparent-@AtechOverlayIconColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN Transparent"]:hover {
    image: url(qss:@IconsLocationFolderName/transparent-@StylesheetIconsColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN Overlay"] {
    image: url(qss:@IconsLocationFolderName/overlay-@AtechOverlayIconColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN Overlay"]:hover {
    image: url(qss:@IconsLocationFolderName/overlay-@StylesheetIconsColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN AutoMode"] {
    image: url(qss:@IconsLocationFolderName/mode-@AtechOverlayIconColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN AutoMode"]:hover {
    image: url(qss:@IconsLocationFolderName/mode-@StylesheetIconsColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN Float"] {
    image: url(qss:@IconsLocationFolderName/float-@AtechOverlayIconColor.svg);
}

Gui--OverlayToolButton[objectName="OBTN Float"]:hover {
    image: url(qss:@IconsLocationFolderName/float-@StylesheetIconsColor.svg);
}

/* The task dialog's Close button: Qt's stock icon is a black X, invisible
   on the dark theme (R118). Same rule as the application sheet, repeated
   because this sheet is the one set on the panel. */
QDialogButtonBox {
    dialog-close-icon: url(qss:@IconsLocationFolderName/close-@StylesheetIconsColor.svg);
}
"""

# Tokens only Atech defines. build_theme.py writes them into both theme
# YAMLs from brand/tokens.py; the overlay sheet is their one reader.
OVERLAY_TOKENS = {"AtechPanelColor": "panel",
                  "AtechHoverColor": "hover",
                  "AtechMutedColor": "muted"}

# Resting colour of the overlay/dock title-bar icons: the suffix of an
# upstream images_classic/<name>-<colour>.svg. Light keeps upstream's
# lightgray (#888 on white reads); dark takes white, because lightgray on the
# dark panel was the low-contrast glyph of R118. Written into the theme
# YAMLs as AtechOverlayIconColor (build_theme.py) and into the app sheets.
OVERLAY_ICON = {"light": "lightgray", "dark": "white"}

# The theme's full-contrast icon colour, as upstream's StylesheetIconsColor
# token names it in FreeCAD Light/Dark.yaml (black / white).
ICONS_COLOR = {"light": "black", "dark": "white"}


def render_overlay():
    """Return the overlay sheet text (mode-free: colours are @Tokens)."""
    return OVERLAY_TEMPLATE


ARROW_ICON = {"light": "darkgray", "dark": "lightgray"}


def render(mode):
    """Return the complete stylesheet text for `mode`."""
    p = tokens.palette(mode)
    return TEMPLATE.format(
        mode=mode,
        # Upstream ships arrow-down-{black,darkgray,lightgray,white,blue}.svg
        # in images_classic/; pick the one that reads on this mode's base.
        arrow_icon=ARROW_ICON[mode],
        overlay_icon=OVERLAY_ICON[mode],
        icons_color=ICONS_COLOR[mode],
        font_body=tokens.FONT_STACK_BODY,
        font_display=tokens.FONT_STACK_DISPLAY,
        font_mono=tokens.FONT_STACK_MONO,
        **p)
